// apps/docs/src/features/docs/components/docs-header.vue
<script setup lang="ts">
  defineProps<{
    sectionTitle: string;
    title: string;
    description: string;
  }>();
</script>

<template>
  <header class="mb-9 space-y-1">
    <p class="font-display text-sm font-medium text-sky-500">{{ sectionTitle }}</p>
    <h1 class="font-display text-3xl tracking-tight text-slate-900 dark:text-white">{{ title }}</h1>
    <p class="pt-3 max-w-3xl text-base text-slate-600 dark:text-slate-400">{{ description }}</p>
  </header>
</template>

// docs/tailwind-plus-syntax/syntax-js/src/components/DocsHeader.jsx
"use client";

import { usePathname } from "next/navigation";

import { navigation } from "@/lib/navigation";

export function DocsHeader({ title }) {
  const pathname = usePathname();
  const section = navigation.find((section) =>
    section.links.find((link) => link.href === pathname)
  );

  if (!(title || section)) {
    return null;
  }

  return (
    <header className="mb-9 space-y-1">
      {section && <p className="font-display font-medium text-sky-500 text-sm">{section.title}</p>}
      {title && (
        <h1 className="font-display text-3xl text-slate-900 tracking-tight dark:text-white">
          {title}
        </h1>
      )}
    </header>
  );
}
