// docs/tailwind-plus-syntax/syntax-js/src/components/TableOfContents.jsx
"use client";

import clsx from "clsx";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

export function TableOfContents({ tableOfContents }) {
  const [currentSection, setCurrentSection] = useState(tableOfContents[0]?.id);

  const getHeadings = useCallback((tableOfContents) => {
    return tableOfContents
      .flatMap((node) => [node.id, ...node.children.map((child) => child.id)])
      .map((id) => {
        const el = document.getElementById(id);
        if (!el) {
          return null;
        }

        const style = window.getComputedStyle(el);
        const scrollMt = Number.parseFloat(style.scrollMarginTop);

        const top = window.scrollY + el.getBoundingClientRect().top - scrollMt;
        return { id, top };
      })
      .filter((x) => x !== null);
  }, []);

  useEffect(() => {
    if (tableOfContents.length === 0) {
      return;
    }
    const headings = getHeadings(tableOfContents);
    function onScroll() {
      const top = window.scrollY;
      let current = headings[0].id;
      for (const heading of headings) {
        if (top >= heading.top - 10) {
          current = heading.id;
        } else {
          break;
        }
      }
      setCurrentSection(current);
    }
    window.addEventListener("scroll", onScroll, { passive: true });
    onScroll();
    return () => {
      window.removeEventListener("scroll", onScroll);
    };
  }, [getHeadings, tableOfContents]);

  function isActive(section) {
    if (section.id === currentSection) {
      return true;
    }
    if (!section.children) {
      return false;
    }
    return section.children.findIndex(isActive) > -1;
  }

  return (
    <div className="hidden xl:sticky xl:top-19 xl:-mr-6 xl:block xl:h-[calc(100vh-4.75rem)] xl:flex-none xl:overflow-y-auto xl:py-16 xl:pr-6">
      <nav aria-labelledby="on-this-page-title" className="w-56">
        {tableOfContents.length > 0 && (
          <>
            <h2
              className="font-display font-medium text-slate-900 text-sm dark:text-white"
              id="on-this-page-title"
            >
              On this page
            </h2>
            <ol className="mt-4 space-y-3 text-sm" role="list">
              {tableOfContents.map((section) => (
                <li key={section.id}>
                  <h3>
                    <Link
                      className={clsx(
                        isActive(section)
                          ? "text-sky-500"
                          : "font-normal text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-300"
                      )}
                      href={`#${section.id}`}
                    >
                      {section.title}
                    </Link>
                  </h3>
                  {section.children.length > 0 && (
                    <ol
                      className="mt-2 space-y-3 pl-5 text-slate-500 dark:text-slate-400"
                      role="list"
                    >
                      {section.children.map((subSection) => (
                        <li key={subSection.id}>
                          <Link
                            className={
                              isActive(subSection)
                                ? "text-sky-500"
                                : "hover:text-slate-600 dark:hover:text-slate-300"
                            }
                            href={`#${subSection.id}`}
                          >
                            {subSection.title}
                          </Link>
                        </li>
                      ))}
                    </ol>
                  )}
                </li>
              ))}
            </ol>
          </>
        )}
      </nav>
    </div>
  );
}

// apps/docs/src/features/docs/components/table-of-contents.vue
<script setup lang="ts">
  import { useActiveSection } from "@/features/docs/composables/use-active-section";
  import type { TocSection } from "@/features/docs/docs-content.types";

  const props = defineProps<{
    sections: readonly TocSection[];
  }>();

  const { currentSectionId, isActive } = useActiveSection(() => props.sections);
</script>

<template>
  <div
    class="hidden xl:sticky xl:top-19 xl:-mr-6 xl:block xl:h-[calc(100vh-4.75rem)] xl:flex-none xl:overflow-y-auto xl:py-16 xl:pr-6"
  >
    <nav aria-labelledby="on-this-page-title" class="w-56">
      <template v-if="sections.length > 0">
        <h2
          id="on-this-page-title"
          class="font-display text-sm font-medium text-slate-900 dark:text-white"
        >
          On this page
        </h2>
        <ol role="list" class="mt-4 space-y-3 text-sm">
          <li v-for="section in sections" :key="section.id">
            <h3>
              <a
                :href="`#${section.id}`"
                :class="
                  isActive(section.id, section.children)
                    ? 'text-sky-500'
                    : 'font-normal text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-300'
                "
              >
                {{ section.title }}
              </a>
            </h3>
            <ol
              v-if="section.children.length > 0"
              role="list"
              class="mt-2 space-y-3 pl-5 text-slate-500 dark:text-slate-400"
            >
              <li v-for="child in section.children" :key="child.id">
                <a
                  :href="`#${child.id}`"
                  :class="currentSectionId === child.id ? 'text-sky-500' : 'hover:text-slate-600 dark:hover:text-slate-300'"
                >
                  {{ child.title }}
                </a>
              </li>
            </ol>
          </li>
        </ol>
      </template>
    </nav>
  </div>
</template>
